#! /usr/bin/ruby

require 'rubygems'
require 'redis'

$0 =~ /_(\d+_\d+_\d+_\d+)_(\d+)$/
ip, port = $1, $2
ip = ip.nil? ? '127.0.0.1' : ip.gsub!(/_/, '.')
port = port.nil? ? 6379 : port

config = ARGV.any? { |a| a =~ /config/ }

if config
  puts "graph_title Redis Slave Lag"
  puts "graph_category redis"
  puts "graph_vlabel lag"
  puts "graph_info This graph monitors the slave lag in seconds"

  puts "lag.label lag"
else
  redis = Redis.new(:host => ip, :port => port)
  info  = redis.info

  puts "lag.value" + " " + info['master_last_io_seconds_ago'].to_s
end
